const ORDER_STATUS = {
  PLACED: 'PLACED',
  PROCESSING: 'PROCESSING',
  READY_TO_SHIP: 'READY_TO_SHIP'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED'
};

const SCHEDULER_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};

const API_MESSAGES = {
  SERVER_HEALTHY: 'Server is running and healthy',
  DATABASE_CONNECTED: 'Database is connected successfully',
  DATABASE_DISCONNECTED: 'Database is disconnected',
  NOT_FOUND: 'Resource not found',
  INTERNAL_SERVER_ERROR: 'An unexpected error occurred'
};

module.exports = {
  ORDER_STATUS,
  PAYMENT_STATUS,
  SCHEDULER_STATUS,
  HTTP_STATUS,
  API_MESSAGES
};
